#
# AD 广告
# 7.2
# 


# ====================分割线====================


hostname = ap*.bilibili.com, *.ixigua.com,*.pstatp.com, homepage-api.smzdm.com, *.39d83s.com, *.googlevideo.com,s.youtube.com,www.youtube.com,youtubei.googleapis.com, photos.adobe.io


# ====================分割线====================


# bilibili 20.5.13 https://github.com/primovist/ScriptsForSurge/blob/master/Scripts/Bilibili.js
^https?:\/\/ap(i|p).(live.)?bilibili.com\/x(live)?\/(resource\/show\/tab|v2\/(reply\/main|view\/material|account\/(mine(\/ipad)?|teenagers\/status)|view|feed\/index|rank|channel\/region\/list)|app-room/v1/index/getInfoByRoom)\?access_key url script-response-body https://raw.githubusercontent.com/primovist/ScriptsForSurge/master/Scripts/Bilibili.js
# JS/AD/bilibili.ad.js
# 如果不行则 https://github.com/NobyDa/Script/blob/master/QuantumultX/Js_local_WorkingCopy.conf

# 电视家 20.7.8 @shuangfan
^http[s]*:\/\/[a-z0-9]+-ad\.ixigua\.com\/[\S]+\.mp4 url 302 https://raw.githubusercontent.com/bv5204978/QXRelay/master/Resource/mp4.mp4
^http[s]*:\/\/[a-z0-9]+-ttcdn-tos\.pstatp\.com\/img\/[\S]+\.jpeg url 302 https://raw.githubusercontent.com/bv5204978/QXRelay/master/Resource/png.png
# ^http[s]*:\/\/[a-z0-9]+-ttcdn-tos\.pstatp\.com\/obj\/union-fe\/playable\/[\S]+\.mp4 url 302 https://raw.githubusercontent.com/bv5204978/QXRelay/master/Resource/mp4.mp4
# https://sf3-ttcdn-tos.pstatp.com/obj/union-fe/playable/c1e49101a1f323bea01b4d75ce1bddd9/88d0c59cbdfd2be67e5d7a9b45b89590.mp4

# 什么值得买.主屏 20.3.7 https://github.com/primovist/ScriptsForSurge/blob/master/Scripts/SMZDM.js
^https?:\/\/homepage-api\.smzdm\.com\/home\?ad url script-response-body https://raw.githubusercontent.com/primovist/ScriptsForSurge/master/Scripts/SMZDM.js
# JS/AD/smzdm.ad.js

# 小小影视 20.7.29 @shuangfan
^https://[a-z0-9]+\.39d83s\.com\/[\S]+\.mp4 url 302 https://raw.githubusercontent.com/bv5204978/QXRelay/master/Resource/mp4.mp4

# YouTube ADS
^https?:\/\/.+\.googlevideo\.com\/.+&oad url reject-img
^https?:\/\/.+\.googlevideo\.com\/.+ctier url reject-img
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/.+ad_ url reject-img
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/.+log_ url reject-img
^https?:\/\/.+\.youtube\.com\/get_midroll_ url reject-img
^https?:\/\/premiumyva\.appspot\.com\/vmclickstoadvertisersite url reject-img
^https?:\/\/.+\.youtube\.com\/api\/stats\/ads url reject-img
^https?:\/\/.+\.youtube\.com\/api\/stats\/.+adformat url reject-img
^https?:\/\/.+\.youtube\.com\/pagead\/ url reject-img
^https?:\/\/.+\.youtube\.com\/ptracking url reject-img

# 知乎 20.4.21 https://github.com/primovist/ScriptsForSurge/blob/master/Scripts/Zhihu.js
^https:\/\/photos\.adobe\.io\/v2\/accounts url script-response-body https://raw.githubusercontent.com/primovist/ScriptsForSurge/master/Scripts/Zhihu.js
# JS/AD/zhihu.ad.js


# ====================分割线====================