#
# AD 广告
# 6.2
#
# 主要源引
# https://github.com/NobyDa/Script/blob/master/README.md
# https://github.com/primovist/ScriptsForSurge/blob/master/ReadMe.md
# 
#


# ====================分割线====================


hostname = ap*.bilibili.com, homepage-api.smzdm.com, *.googlevideo.com,s.youtube.com,www.youtube.com,youtubei.googleapis.com


# ====================分割线====================


# bilibili 20.5.13 https://github.com/primovist/ScriptsForSurge/blob/master/Scripts/Bilibili.js
^https?:\/\/ap(i|p).(live.)?bilibili.com\/x(live)?\/(resource\/show\/tab|v2\/(reply\/main|view\/material|account\/(mine(\/ipad)?|teenagers\/status)|view|feed\/index|rank|channel\/region\/list)|app-room/v1/index/getInfoByRoom)\?access_key url script-response-body JS/AD/bilibili.ad.js
# 如果不行则 https://github.com/NobyDa/Script/blob/master/QuantumultX/Js_local_WorkingCopy.conf

# 什么值得买.主屏 20.3.7 https://github.com/primovist/ScriptsForSurge/blob/master/Scripts/SMZDM.js
^https?:\/\/homepage-api\.smzdm\.com\/home\?ad url script-response-body JS/AD/smzdm.ad.js

# YouTube ADS
^https?:\/\/.+\.googlevideo\.com\/.+&oad url reject-img
^https?:\/\/.+\.googlevideo\.com\/.+ctier url reject-img
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/.+ad_ url reject-img
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/.+log_ url reject-img
^https?:\/\/.+\.youtube\.com\/get_midroll_ url reject-img
^https?:\/\/premiumyva\.appspot\.com\/vmclickstoadvertisersite url reject-img
^https?:\/\/.+\.youtube\.com\/api\/stats\/ads url reject-img
^https?:\/\/.+\.youtube\.com\/api\/stats\/.+adformat url reject-img
^https?:\/\/.+\.youtube\.com\/pagead\/ url reject-img
^https?:\/\/.+\.youtube\.com\/ptracking url reject-img


# ====================分割线====================